name: Trigger AlmaLinux 9 Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 130.00beta01
    paths-ignore:
      - '.gitignore'
      - 'readme.txt'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.github/workflows/main.yml'
      - '.github/workflows/cmm-almalinux9.yml'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trigger centminmod-workflows workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: centminmod/centminmod-workflows
          event-type: run-almalinux-9-workflow
